pool:
  vmImage: 'Ubuntu-16.04'

trigger:
  branches:
    include:
    - master
    - features/*
  paths:
    exclude:
    - .editorconfig
    - LICENSE
    - README.md
    - appveyor.yml
    - .travis.yml
    - .circleci/config.yml

steps:
- bash: |
    dotnet tool install --global Cake.Tool --version 0.31.0
  displayName: 'Install "Cake.Tool" .NET Core global tool'

- bash: |
    export PATH="$PATH:$HOME/.dotnet/tools"
    dotnet cake build.cake --bootstrap
    dotnet cake build.cake --pack
  displayName: 'Build'
