pool:
  vmImage: 'Ubuntu-16.04'

trigger:
  branches:
    include:
    - master
    - features/*
  paths:
    exclude:
    - .editorconfig
    - LICENSE
    - README.md
    - appveyor.yml
    - .travis.yml
    - .circleci/config.yml

steps:
- bash: |
    ./build/dotnet-install.sh --channel Current
  displayName: 'Install Current .NET Core SDK'

- bash: |
    dotnet tool install --global Cake.Tool --version 0.31.0
  displayName: 'Install "Cake.Tool" .NET Core global tool'

- bash: |
    export PATH="$PATH:$HOME/.dotnet/tools"
    dotnet cake build.cake --bootstrap
    dotnet cake build.cake --pack
  displayName: 'Build'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'xUnit'
    testResultsFiles: '*.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)/artifacts/tests-results'
  condition: succeededOrFailed()
  displayName: 'Publish Test Results'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'NuGet packages'
    targetPath: 'artifacts/packages'
  displayName: 'Publish NuGet packages'
