pool:
  vmImage: 'Ubuntu-18.04'

trigger:
  branches:
    include:
    - master
    - features/*
  paths:
    exclude:
    - .editorconfig
    - LICENSE
    - README.md
    - appveyor.yml
    - .travis.yml
    - .circleci/config.yml

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK 3.1.202'
  inputs:
    packageType: sdk
    version: 3.1.202
    installationPath: $(Agent.ToolsDirectory)/dotnet

- bash: |
    dotnet tool install --global Cake.Tool --version 0.37.0
  displayName: 'Install "Cake.Tool" .NET Core global tool'

- bash: |
    export PATH="$PATH:$HOME/.dotnet/tools"
    export PATH="$HOME/.dotnet:$PATH"
    dotnet cake build.cake --bootstrap
    dotnet cake build.cake --pack
  displayName: 'Build'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'xUnit'
    testResultsFiles: '*.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)/artifacts/tests-results'
  condition: succeededOrFailed()
  displayName: 'Publish Test Results'

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: 'NuGet packages'
    targetPath: 'artifacts/packages'
  displayName: 'Publish NuGet packages'
