pool:
  vmImage: ubuntu-20.04

trigger:
  branches:
    include:
    - main
    - features/*
  paths:
    exclude:
    - .circleci/config.yml
    - .github/workflows/build.yml
    - .vscode/**
    - appveyor.yml
    - LICENSE
    - README.md

steps:
- task: UseDotNet@2
  displayName: 'Install .NET SDK 6.0.100'
  inputs:
    packageType: sdk
    version: 6.0.100
    installationPath: $(Agent.ToolsDirectory)/dotnet

- bash: |
    dotnet tool restore
  displayName: 'Restoring "Cake.Tool" .NET local tool'

- bash: |
    export PATH="$PATH:$HOME/.dotnet/tools"
    export PATH="$HOME/.dotnet:$PATH"
    dotnet cake build.cake --bootstrap
    dotnet cake build.cake --pack
  displayName: 'Build'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '*.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)/artifacts/test-results/junit'
  condition: succeededOrFailed()
  displayName: 'Publish Test Results'

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: 'NuGet packages'
    targetPath: 'artifacts/packages'
  displayName: 'Publish NuGet packages'
