version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0-focal
    steps:
      - checkout
      - run:
          name: Restore "Cake.Tool" .NET Core local tool
          command: |
            dotnet tool restore
      - run:
          name: Build
          command: |
            export PATH="$PATH:$HOME/.dotnet/tools"
            dotnet cake build.cake --bootstrap
            dotnet cake build.cake --pack
      - store_artifacts:
          name: Uploading NuGet packages as artifacts
          path: artifacts/packages
          destination: packages
      - store_artifacts:
          name: Uploading xUnit test results as artifacts
          path: artifacts/tests-results
          destination: tests-results-xunit
      - store_artifacts:
          name: Uploading JUnit test results as artifacts
          path: artifacts/junit
          destination: tests-results-junit
      - store_test_results:
          # CircleCI infers the name of the testing framework from the containing folder
          path: artifacts/junit

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
                - /features\/.*/
