version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0
    steps:
      - checkout
      - run:
          name: Restore "Cake.Tool" .NET local tool
          command: |
            dotnet tool restore
      - run:
          name: Build
          command: |
            export PATH="$PATH:$HOME/.dotnet/tools"
            dotnet cake build.cake --bootstrap
            dotnet cake build.cake --pack
      - store_artifacts:
          name: Uploading NuGet packages as artifacts
          path: artifacts/packages
          destination: packages
      - store_artifacts:
          name: Uploading JUnit test results as artifacts
          path: artifacts/test-results/junit
          destination: tests-results-junit
      - store_test_results:
          # CircleCI infers the name of the testing framework from the containing folder
          path: artifacts/test-results

workflows:
  version: 2
  build:
    jobs:
      - build
