version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1.202-bionic
    steps:
      - checkout
      - run:
          name: Install "Cake.Tool" .NET Core global tool
          command: |
            export PATH="$PATH:$HOME/.dotnet/tools"
            dotnet tool install -g Cake.Tool --version 0.35.0
      - run:
          name: Install libcurl3 for GitVersion
          command: |
            apt-get update
            apt-get install -qq -y libcurl3
      - run:
          name: Build
          command: |
            export PATH="$PATH:$HOME/.dotnet/tools"
            dotnet cake build.cake --bootstrap
            dotnet cake build.cake --pack
      - store_artifacts:
          name: Uploading NuGet packages as artifacts
          path: artifacts/packages
          destination: packages
      - store_artifacts:
          name: Uploading xUnit test results as artifacts
          path: artifacts/tests-results
          destination: tests-results-xunit
      - store_artifacts:
          name: Uploading JUnit test results as artifacts
          path: artifacts/junit/xUnit
          destination: tests-results-junit
      - store_test_results:
          # CircleCI infer the name of the testing framework from the containing folder
          path: artifacts/junit