version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2.100-sdk-bionic
    steps:
      - checkout
      - run:
          name: Make scripts executable
          command: |
            chmod +x ./build.sh
      - run:
          name: Install Cake.Tool .NET Core global tool
          command: |
            export PATH="$PATH:/root/.dotnet/tools"
            dotnet tool install -g Cake.Tool --version 0.31.0
      - run:
          name: Build
          command: |
            export PATH="$PATH:/root/.dotnet/tools"
            dotnet nuget locals all --list
            dotnet cake build.cake --exclusive
            find /root/.nuget/packages/GitVersion.CommandLine.DotNetCore/gitversion.commandline.dotnetcore/4.0.0/tools/lib/linux/x86_64 -name '*.so' -type f -print | xargs ldd | grep 'not found'
      - store_artifacts:
          name: Uploading NuGet packages as artifacts
          path: artifacts/packages
          destination: packages
      - store_artifacts:
          name: Uploading xUnit test results as artifacts
          path: artifacts/tests-results
          destination: tests-results-xunit
      - store_artifacts:
          name: Uploading JUnit test results as artifacts
          path: artifacts/junit/xUnit
          destination: tests-results-junit
      - store_test_results:
          # CircleCI infer the name of the testing framework from the containing folder
          path: artifacts/junit