version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2.100-sdk-bionic
    steps:
      - checkout
      - run:
          name: Make scripts executable
          command: |
            chmod +x ./build.sh
      - run:
          name: Install Mono
          command: |
            apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
            echo "deb http://download.mono-project.com/repo/ubuntu stable-bionic main" | tee /etc/apt/sources.list.d/mono-stable-official.list
            apt-get update
            apt-get -qq -y install mono-complete
      - run:
          name: List missing required packages for GitVersion
          command: |
            ./build.sh --exclusive
            find ./tools/GitVersion.CommandLine.DotNetCore/tools/lib/linux/x86_64 -name '*.so' -type f -print | xargs ldd | grep 'not found'
      - store_artifacts:
          name: Uploading NuGet packages as artifacts
          path: artifacts/packages
          destination: packages
      - store_artifacts:
          name: Uploading xUnit test results as artifacts
          path: artifacts/tests-results
          destination: tests-results-xunit
      - store_artifacts:
          name: Uploading JUnit test results as artifacts
          path: artifacts/junit/xUnit
          destination: tests-results-junit
      - store_test_results:
          # CircleCI infer the name of the testing framework from the containing folder
          path: artifacts/junit