name: Build
on:
  push:
    branches:
      - main
      - 'features/**'
      - 'gh-actions/**'
    paths-ignore:
      - .editorconfig
      - LICENSE
      - README.md
      - appveyor.yml
      - .circleci/config.yml
      - azure-pipelines.yml
jobs:
  Build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install latest .NET SDK
        run: .\build\dotnet-install.ps1
      - name: Restore .NET tools
        run: dotnet tool restore
      - name: Build
        run: |
          dotnet cake build.cake --bootstrap
          dotnet cake build.cake --pack
      - name: Upload NuGet packages
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: .\artifacts\packages
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v2
        with:
          name: tests-results
          path: .\artifacts\tests-results\*.xml
        if: ${{ always() }}