name: Build
on:
  push:
    branches:
      - main
      - 'features/**'
      - 'gh-actions/**'
    paths-ignore:
      - .editorconfig
      - LICENSE
      - README.md
      - appveyor.yml
      - .circleci/config.yml
      - azure-pipelines.yml
jobs:
  Build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install latest .NET SDK
        run: .\build\dotnet-install.ps1
      - name: Restore .NET tools
        run: dotnet tool restore
      - name: Build
        run: |
          dotnet cake build.cake --bootstrap
          dotnet cake build.cake --pack
      - name: Upload NuGet packages
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: .\artifacts\packages
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v2
        with:
          name: tests-results
          path: .\artifacts\test-results\trx\*.trx
        if: ${{ always() }}
      - name: Report test results
        uses: dorny/test-reporter@v1.5.0
        continue-on-error: true
        if: ${{ always() }}
        with:
          name: Test results
          path: 'artifacts/test-results/trx/*.trx'
          reporter: dotnet-trx
      - name: Create GitHub release on main branch
        uses: softprops/action-gh-release@v0.1.14
        if: ${{ github.ref_name == 'main' }}
        with:
          files: 'artifacts/packages/*'
          prerelease: true
          fail_on_unmatched_files: true
          tag_name: 'v${{ env.PACKAGE_VERSION }}'
      - name: Create GitHub prerelease on features branches
        uses: softprops/action-gh-release@v0.1.14
        if: ${{ startsWith(github.ref_name, 'features/') }}
        with:
          files: 'artifacts/packages/*'
          prerelease: false
          fail_on_unmatched_files: true
          tag_name: 'v${{ env.PACKAGE_VERSION }}'