name: Build
on:
  pull_request:
    branches:
      - main
    paths:
      - .circleci/config.yml
      - .github/workflows/security-scanning-csharp.yml
      - .github/workflows/skipped-build.yml
      - .github/dependabot.yml
      - '.vscode/**'
      - appveyor.yml
      - azure-pipelines.yml
      - LICENSE
      - README.md
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Handling skipped but required check, see https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks"
